version: '3.7'
services: 
  web:
    build: .
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 0
    ports:
      - "8000:8000"
    links:
      - db
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    command: python3 ./manage.py runserver 0.0.0.0:8000

  db:
    image: mariadb
    env_file:
      - .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --slow-query-log=1 --thread-cache-size=5 --long-query-time=3
    environment:
      - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root"
    secrets:
      - mysql-root
secrets:
  mysql-root:
    file: ./secrets/mysql-root