# Generated by Django 3.0.8 on 2020-08-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200620_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesets', to='docs.Document', verbose_name='document'),
        ),
    ]
