# Generated by Django 3.0.8 on 2020-08-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20200802_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filesets', to='docs.Document', verbose_name='document'),
        ),
    ]
